apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-test-rc
spec:
  replicas: 1
  selector: 
    app: jenkins-test-rc-pod
  template:
    metadata:
      labels:
        app: jenkins-test-rc-pod
    spec:
      containers:    
      - name: jenkins
        image: jenkins:2.60.3
        ports:
        - containerPort: 803
